### ISSUE TITLE
Breaking with serverless v0.5?

### ISSUE THREAD

**Issue by thenikso** [asprouse/serverless-webpack-plugin#10]
Hello there! serverless 0.5 isn't working here:

```
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Class extends value #<Serverless> is not a function or null
    at getPlugin (/my-serverless-project/node_modules/serverless-webpack-plugin/index.js:6:35)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

any clue?

Thanks!

**Comment by thewillhuang** [comment]
yeah, i've been running into the same issues, i don't see any changes from the plugin starter from https://github.com/serverless/serverless-plugin-boilerplate anyway, i've deleted and reinstall serverless from scratch several times trying to update to 0.5 using this plugin

**Comment by asprouse** [comment]
I haven't looked at 0.5 but @ac360 mentioned in the gitter that 0.5 would significantly change the plugin. I haven't updated to 0.5 yet. I will take a look at what needs to change to have 0.5 compatibility. For now I will just make a note on the readme.

**Comment by thenikso** [comment]
Indeed the whole optimization phase seems to have changed judging by https://github.com/serverless/serverless-runtime-babel

**Comment by andreipopovici** [comment]
Here are the breaking changes for serverless v0.5: https://github.com/serverless/serverless/releases/tag/v0.5.0

Notably, `s-component.json` is gone, so there needs to be another place to read the config file path from, perhaps `s-project.json`?

Also, it now passes the Serverless instance, instead of a ServerlessClass, whatever that means. Here's the new way to write plugins: http://docs.serverless.com/v0.5.0/docs/plugins

Breaking changes suck :( Alas, it's supposedly for the best.

**Comment by asprouse** [comment]
@andreipopovici I have a version locally which take these changes into account. Unfortunately it's not that simple. They have also changed the way that they handle variables, by writing out a wrapper script that bootstraps `process.env` instead of requiring [serverless-helpers-js](https://github.com/serverless/serverless-helpers-js). Instead of reading your source files directly (ie `project/function/handler.js` the plugin now has to read from `pathDist` where this file is generated `project/_meta/_tmp/function@1459443401183/_serverless_handler.js` this messes up the context path and requires you to copy any library functions and node_modules to `project/_meta/_tmp/function@1459443401183` which is really slow.

Unfortunately context and entry cannot be absolute paths and the only way to get this to work is to generate `_serverless_handler.js` next to `project/function/handler.js`. In order to override this path you I would need to extend the nodejs runtime of serverless. As @thenikso pointed out runtimes control both the running and the build of your functions. So the way forward is to convert this plugin into a runtime which uses webpack for the build step. The dilemma here is that Runtimes couple both run and build functions and while it's clear we want to build with webpack it's unclear how to handle the run function.

Webpack is a by definition a build tool and what loaders you configure actually specify the runtime. In my case I use the babel loader so my use case is similar to [serverless-runtime-babel](https://github.com/serverless/serverless-runtime-babel) except wanting webpack as the build tool. However if I create a `babel-webpack` runtime as a replacement for this plugin I am now making the assumption that everyone is using babel and not coffeescript or typescript, etc.

I think that the ultimate solution is to separate the running and building of code to separate plugins or at least allow plugins to override the build step without creating an entirely new runtime. Ultimately people are gonna want to change how the build step works whether they want Browserify with config options that aren't available in [serverless-runtime-babel](https://github.com/serverless/serverless-runtime-babel), [webpack](https://github.com/webpack/webpack) or even [rollup](https://github.com/webpack/webpack). I think  that @ac360 should weigh in on this.

I am not sure how to move forward and would like some feedback as to how everyone is using this plugin.
